import Link from "next/link";
import { ChevronRight, Sparkles } from "lucide-react";
import { buttonClasses } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { AiGlyph } from "@/components/ui/ai-glyph";
import { BrowserFrame } from "@/components/preview/browser-frame";
import { FigmaCanvas } from "@/components/preview/figma-canvas";
import { MiniSite, ScaledSite } from "@/components/preview/mini-site";

const BRAND = "Northwind";
const HEADLINE = "Ship your ideas without the rebuild.";

export function Hero() {
  return (
    <section className="relative overflow-hidden px-5 pb-16 pt-16 md:px-10 md:pt-20 lg:px-20 lg:pt-24">
      <div aria-hidden className="hero-grid pointer-events-none absolute inset-0 opacity-35" />

      <div className="relative mx-auto max-w-[820px] text-center">
        <Badge className="mx-auto">
          <AiGlyph />
          Now reading Figma variables and auto layout
        </Badge>
        <h1 className="mt-5 text-[40px] font-extrabold leading-[1.05] tracking-[-0.03em] md:text-[56px] lg:text-display">
          Your Figma design.
          <br />
          Your website.
          <br />
          Generated by AI.
        </h1>
        <p className="mx-auto mt-5 max-w-prose text-body md:text-body-lg text-content-secondary">
          Transform pixel-perfect Figma designs into responsive, production-ready websites without rebuilding your UI
          from scratch.
        </p>
        <div className="mt-8 flex flex-wrap items-center justify-center gap-3">
          <Link href="/signup" className={buttonClasses("primary", "lg")}>Start building</Link>
          <Link href="#how" className={buttonClasses("secondary", "lg")}>See how it works</Link>
        </div>
        <p className="mt-4 text-caption text-content-muted">
          Free to try · No credit card · Export the code any time
        </p>
      </div>

      <div className="relative mx-auto mt-14 grid max-w-container items-center gap-6 lg:grid-cols-[1fr_160px_1fr] lg:gap-0">
        <figure className="overflow-hidden rounded-[14px] border border-border bg-bg-surface shadow-lg">
          <figcaption className="flex h-10 items-center gap-2 border-b border-border px-3.5 text-caption text-content-muted">
            <span aria-hidden className="flex gap-1.5">
              {[0, 1, 2].map((i) => <i key={i} className="h-2.5 w-2.5 rounded-full bg-border-strong" />)}
            </span>
            Marketing site — Figma
            <span className="ml-auto rounded-full bg-bg-subtle px-2 py-0.5 text-[11px] text-content-secondary">
              Frame · 1440
            </span>
          </figcaption>
          <FigmaCanvas
            className="h-[300px] p-6"
            regions={[{ name: "Hero", top: "64px", height: "104px", left: "24px", right: "24px" }]}
          >
            <ScaledSite scale={0.92} height={264} className="border border-[#DADADA]">
              <MiniSite brand={BRAND} headline={HEADLINE} />
            </ScaledSite>
          </FigmaCanvas>
        </figure>

        <div className="relative flex flex-col items-center gap-2.5">
          <div aria-hidden className="absolute inset-x-0 top-1/2 hidden h-px bg-[repeating-linear-gradient(90deg,var(--border-strong)_0_6px,transparent_6px_12px)] lg:block" />
          <ChevronRight aria-hidden className="absolute left-3.5 top-1/2 hidden h-4 w-4 -translate-y-1/2 text-border-strong lg:block" />
          <ChevronRight aria-hidden className="absolute right-3.5 top-1/2 hidden h-4 w-4 -translate-y-1/2 text-border-strong lg:block" />
          <div className="relative grid h-16 w-16 place-items-center rounded-[18px] bg-bg-dark shadow-[0_12px_30px_-8px_rgba(17,17,17,.4)]">
            <Sparkles aria-hidden className="h-6 w-6 text-white" />
            <span aria-hidden className="absolute -inset-1.5 rounded-[24px] border border-accent/50" />
          </div>
          <p className="relative bg-bg px-1.5 text-center text-[11px] font-medium text-content-muted">
            Analysing layout, tokens, components
          </p>
        </div>

        <BrowserFrame url="northwind.vercel.app">
          <ScaledSite scale={1.9} height={300}>
            <MiniSite brand={BRAND} headline={HEADLINE} />
          </ScaledSite>
        </BrowserFrame>
      </div>
    </section>
  );
}
