import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth/session";
import { listProjects } from "@/lib/repositories/projects";
import { getLatestVersionFiles, readFile } from "@/lib/repositories/code";
import { createZip, type ZipEntry } from "@/lib/code/zip";

/**
 * Downloads a project's generated code.
 *
 * Generated code had no way out of the database. The Code screen could show it,
 * the marketing page offered "Download repository", the deploy screen offered
 * to ship it — and none of those did anything, so the one thing a user most
 * wants after a generation was the one thing the product could not do.
 *
 * Authorised through the user's own RLS-scoped client, via the project list:
 * an id that is not theirs simply is not found.
 */
export const dynamic = "force-dynamic";
/** Reading offloaded files is one storage round trip each. */
export const maxDuration = 60;

export async function GET(_request: Request, context: { params: Promise<{ id: string }> }) {
  const { id } = await context.params;

  const session = await getSession();
  if (!session || session.demo) {
    return NextResponse.json({ error: "Sign in to download your generated code." }, { status: 401 });
  }

  const owned = await listProjects(session, 50);
  const project = owned.find((candidate) => candidate.id === id || candidate.slug === id);
  if (!project) {
    return NextResponse.json({ error: "No such project." }, { status: 404 });
  }

  const version = await getLatestVersionFiles(project.id);
  if (!version || version.files.length === 0) {
    return NextResponse.json(
      { error: "This project has not generated any code yet." },
      { status: 409 },
    );
  }

  // Most files are inline; the ones past the inline threshold live in object
  // storage and are fetched individually, under the same JWT.
  const entries: ZipEntry[] = [];
  for (const file of version.files) {
    const content = file.content ?? (await readFile(version.versionId, file.path));
    if (content === null) continue;
    entries.push({ path: file.path, content });
  }

  if (entries.length === 0) {
    return NextResponse.json({ error: "None of this version's files could be read." }, { status: 409 });
  }

  // A note in the archive, so a file opened weeks later still says where it
  // came from and — importantly — that nothing compiled it.
  entries.push({
    path: "PIXELFORGE.md",
    content: [
      `# ${project.name}`,
      "",
      `Generated by PixelForge AI · version ${version.versionNumber}`,
      `Exported ${new Date().toISOString()}`,
      "",
      `- Framework: ${project.framework}`,
      `- Styling: ${project.styling}`,
      `- TypeScript: ${project.typescript ? "yes" : "no"}`,
      `- Files: ${entries.length}`,
      version.summary ? `- Summary: ${version.summary}` : "",
      "",
      "This code has not been compiled or run. Install dependencies and build it",
      "before deploying.",
      "",
    ].join("\n"),
  });

  let archive: Buffer;
  try {
    archive = createZip(entries);
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Could not build the archive." },
      { status: 500 },
    );
  }

  const filename = `${project.slug}-v${version.versionNumber}.zip`;

  return new NextResponse(new Uint8Array(archive), {
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Content-Length": String(archive.length),
      // Contains the user's own source; never let an intermediary hold it.
      "Cache-Control": "private, no-store",
    },
  });
}
